name: syncserve
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Josefin Sans
      fonts: 
        - asset: assets/fonts/JosefinSansRomanBold.ttf
          weight: 700
    - family: Inria Sans
      fonts: 
        - asset: assets/fonts/InriaSansBold.ttf
          weight: 700
        - asset: assets/fonts/InriaSansRegular.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratLight.ttf
          weight: 300
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansBold.ttf
          weight: 700
    - family: Averia Serif Libre
      fonts: 
        - asset: assets/fonts/AveriaSerifLibreItalic.ttf
          weight: 400
    - family: ABeeZee
      fonts: 
        - asset: assets/fonts/ABeeZeeItalic.ttf
          weight: 400
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishMedium.ttf
          weight: 500
